### ISSUE TITLE
Support for additional environment variables, THUMB_LOCATION and ENCODED_VIDEO_LOCATION

### ISSUE THREAD

**Issue by vhsdream** [loeeeee/immich-in-lxc#50] opened 2024-10-27 13:08 UTC
Hi, I noticed something after I managed ro successfully deploy immich in LXC, using my bind-mounted SMB share as the upload location. The thumbnail and encoded-video folders are also automatically created on the share (which is just an array of HDDs). So when adding new photos, or an external library, the generated thumbnails and encoded videos are created on the share, which seems to impact performance when scrolling through the library. It also seem to take longer to generate the files.

It would be much better to have the thumbnail and video folders located on the faster internal storage, so I looked into being able to do that. According to [this](https://immich.app/docs/guides/custom-locations) it is possible (at least in the Docker version) via the use of environment variables THUMB_LOCATION and ENCODED_VIDEO_LOCATION. However in my limited attempts so far I have been unable to get it to work. I added them in the runtime.env file thinking that would work but it doesn't.

I thought I might be able to put these in the .env file before rebuilding immich but then I think the install.sh script needs to be able to handle these so it would require modification.

Perhaps symlinking might work as well, so I am going to try that next and see what kind of disaster happens.

**Comment by vhsdream** [comment] 2024-10-27 15:05
OK back with an update. I cannot create a symlink from the SMB share to the location I want the thumbs and video folders to be. That is probably a limitation that is intended or built-in or whatever.

So I rebuilt immich, and instead chose to have the upload folder (which contains upload/ encoded-video/ profile/ thumbs/ and library/) be on the internal filesystem. Then I ran it once and set things up, and shut it down. Then I symlinked the upload/ folder to the location of my mounted SMB share. And this seems to work. Now when I upload photos, they are uploaded to the SMB share as intended, but thumbnails and encoded videos are on the internal drive still. 

A side effect of that is that the Storage space indicator at the bottom left shows the space left on the internal drive instead of the SMB share, but I noticed that in the Server Stats area it still correctly calculates the amount of space used on the SMB share, since it is using the metadata of each file to calculate that.

I guess this can be closed, unless you agree that it would be a useful feature to be able to customize the locations in your script via the environment variables I mentioned above.

**Comment by loeeeee** [comment] 2024-10-27 17:57
> However in my limited attempts so far I have been unable to get it to work. I added them in the runtime.env file thinking that would work but it doesn't.

**That is interesting. I did not notice that. I will note this and test it (in the future) to see what is actually happening. (Note to future self)**  Right now, I have some important thing at hands. Sorry about that.

> I thought I might be able to put these in the .env file before rebuilding immich but then I think the install.sh script needs to be able to handle these so it would require modification.

I sort of handles the `THUMB_LOCATION` problem in a different way. Hear me out. The install script will create a folder at `$INSTALL_DIR` called `upload`, and when the immich is built inside the folder, `$INSTALL_DIR/app`, the script will soft link `$INSTALL_DIR/upload` to `$INSTALL_DIR/app/upload`, so that during rebuild, the thumbnails, user uploads, etc. persist.

To accomplish a custom `THUMB_LOCATION`, one can try soft link the folders inside the `$INSTALL_DIR/upload` to where ever they want. Wala, we got THUMB_LOCATION and ENCODED_VIDEO_LOCATION.

I write this down anyway, definitely not because I did not finish reading. It is because I could later copy-and-paste it to the tutorial. 🤡 

> .. and instead chose to have the upload folder (which contains upload/ encoded-video/ profile/ thumbs/ and library/) be on the internal filesystem. Then I ran it once and set things up, and shut it down. Then I symlinked the upload/ folder to the location of my mounted SMB share. And this seems to work.

Congrats! You figured it out by yourself! 😃 My own instance of Immich uses this exact method as well. No issues, at least not yet, I think. 

> A side effect of that is that the Storage space indicator at the bottom left shows the space left on the internal drive instead of the SMB share, but I noticed that in the Server Stats area it still correctly calculates the amount of space used on the SMB share, since it is using the metadata of each file to calculate that.

I think the admin account can show the usage of total space. I guess the docker build of Immich may have the same issue as well. Just guessing. Also, keep an eye on the space left on the internal storage, thumbnails and videos can take up lots of spaces.

> I guess this can be closed, unless you agree that it would be a useful feature to be able to customize the locations in your script via the environment variables I mentioned above.

My personal opinion is that it would be easier to do it the simple way. It is not broken, so don't fix it.

Thanks for your time for trying this out and valuable opinions!

**Comment by loeeeee** [comment] 2024-10-27 17:59
Also, this seems to be a duplicate of issue #8. But whatever, this has more context. 😄

**Closed by loeeeee** 2024-10-27 17:59 UTC
